int isdigit(int c);
int isalpha(int c);
int isalphnum(const char *sp);
int isalnum(int c);
int iscntrl(int c);
int islower(int c);
int isupper(int c);
int isspace(int c);
int isxdigit(int c);
int ispunct(int c);
int isgraph(int c);
int tolower(int c);
int toupper(int c);
